baseURL = "http://luoqi.tech/"
languageCode = "zh-CN"
title = "ERYUESANHI"
theme = "ananke"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  favicon = "/images/cloud.ico"
  site_logo = "/images/favicon.ico"
  description = ""
  #facebook = ""
  #twitter = ""
  #instagram = ""
  #youtube = ""
  zhihu = "123"
  github = "https://github.com/logeexpluoqi"
  #gitlab = ""
  #linkedin = ""
  #mastodon = ""
  #slack = ""
  #stackoverflow = ""
  #rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-ashed-blue"
  featured_image = "/images/乡村.png"
  recent_posts_number = 2